version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "torch"
      - dependency-name: "torchvision"
      - dependency-name: "torchaudio"