name: music-catalog-manager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit
    - pandas
    - numpy
    - matplotlib
    - scikit-learn
    - torch
    - altair
    - watchdog
    - pytest
    - pytest-cov
    - requests
    - tornado
