name: music-catalog-manager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit>=1.0,<2.0
    - pandas>=1.0,<3.0
    - numpy>=1.21,<2.0
    - matplotlib>=3.0,<4.0
    - scikit-learn>=0.24,<2.0
    - torch>=1.10,<3.0
    - altair>=4.0,<6.0
    - watchdog>=2.0,<3.0
    - tornado>=6.0,<7.0  # Fixed to avoid mismatch issues
