name: CI with Conda and Locked Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9

    - name: Install Dependencies from Lock File
      run: |
        conda install -c conda-forge conda-lock
        conda-lock install --name music-catalog-manager

    - name: Run Tests
      run: |
        conda activate music-catalog-manager
        pytest
