name: Python package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda 
        uses: conda-incubator/setup-miniconda@v2 
        with:
          auto-update-conda: true 
          python-version: 3.9 
          environment-file: environment.yml 
          activate-environment: music-catalog-manager 

      - name: Install pip-tools and compile requirements.txt 
        run: |
          pip install pip-tools 
          pip-compile --output-file=requirements.txt requirements.in 

      - name: Install dependencies  
        run: |
          conda env update --file environment.yml --name music-catalog-manager || echo "Conda failed, falling back to pip."  
          pip install -r requirements.txt || echo "Pip installation failed, check requirements."  

      # Rest of workflow...
