name: Python package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        environment-file: environment.yml
        activate-environment: music-catalog-manager

    - name: Install Dependencies with Fallback
      run: |
        echo "Attempting to install dependencies using Conda..."
        conda env update --file environment.yml --name music-catalog-manager || echo "Conda failed, falling back to pip."
        pip install -r requirements.txt || echo "Pip installation failed, check requirements."

    - name: Validate Dependencies
      run: |
        echo "Checking dependency compatibility..."
        pip check || echo "Dependency validation failed, review dependencies."

    - name: Run Tests
      run: |
        pytest

    - name: Generate Lock File
      run: |
        echo "Generating conda-lock file for reproducibility..."
        conda install -c conda-forge conda-lock
        conda-lock lock --file environment.yml
