name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment
      run: conda activate myenv

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest