name: Python package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        environment-file: .github/python-package-conda.yml
        activate-environment: myenv

    - name: Install dependencies
      run: |
        conda env update --file .github/python-package-conda.yml --name myenv
        conda activate myenv
        pip install -r requirements.txt

    - name: Run tests
      run: |
        conda activate myenv
        pytest
