name: Python package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9  # Ensure this matches the Python version in environment.yml
        environment-file: environment.yml  # Ensure this file is correctly set up
        activate-environment: music-catalog-manager  # Matches the environment name in environment.yml

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name music-catalog-manager
        conda activate music-catalog-manager
        pip install -r requirements.txt

    - name: Run tests
      run: |
        conda activate music-catalog-manager
        pytest  # Adjust this command to run your tests
