name: CI with Conda and Locked Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9

    # Step 3: Install conda-lock
    - name: Install Conda-Lock
      run: |
        echo "Installing conda-lock..."
        conda install -c conda-forge conda-lock -y

    # Step 4: Verify conda-lock installation
    - name: Verify Conda-Lock Installation
      run: |
        echo "Checking conda-lock version..."
        conda-lock --version || exit 1

    # Step 5: Generate environment from lock file
    - name: Generate Environment from Lock File
      run: |
        echo "Creating environment from conda-lock..."
        conda-lock install --name music-catalog-manager || exit 1

    # Step 6: Run tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        conda activate music-catalog-manager
        pytest || exit 1

    # Optional Step: Report coverage (if applicable)
    - name: Upload Test Results (Optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: coverage.xml
