name: CI with Conda and Locked Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9

    - name: Install Dependencies
      run: |
        echo "Installing dependencies using conda-lock..."
        conda install -c conda-forge conda-lock || exit 1
        conda-lock install --name music-catalog-manager || exit 1

    - name: Validate Dependencies
      run: |
        echo "Validating installed dependencies..."
        pip check || echo "Warning: Dependency issues found, review required."

    - name: Verify pytest Installation
      run: |
        echo "Checking if pytest is installed..."
        pytest --version || echo "pytest not found, check dependencies."

    - name: Run Tests
      run: |
        echo "Running tests with pytest..."
        pytest --cov=. || exit 1

    - name: Generate Lock File
      run: |
        echo "Generating conda-lock file..."
        conda-lock lock --file environment.yml || exit 1

    - name: Upload Test Results (Optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: coverage.xml
