name: CI with Conda and Locked Dependencies

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: music-catalog-manager
        auto-update-conda: true
        python-version: 3.9
        environment-file: environment.yml
        use-mamba: true
    
    - name: Install conda-lock
      run: conda install -c conda-forge conda-lock

    - name: Check conda-lock version
      run: conda-lock --version

    - name: Install dependencies with conda
      run: |
        conda env update --file environment.yml --name music-catalog-manager || echo "Conda failed, falling back to pip."
        pip install -r requirements.txt || echo "Pip installation failed, check requirements."
        pip install pycairo

    - name: Validate dependencies
      run: pip check || echo "Dependency validation failed, review dependencies."

    - name: Run tests
      run: pytest