name: Python package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        environment-file: environment.yml
        activate-environment: music-catalog-manager

    - name: Install Dependencies with Fallback
      run: |
        echo "Installing dependencies using Conda..."
        conda env update --file environment.yml || echo "Conda failed, trying pip"
        pip install -r requirements.txt || echo "Pip failed, skipping..."

    - name: Validate Dependencies
      run: |
        echo "Validating installed dependencies..."
        pip check || echo "Dependency validation failed, review dependencies."

    - name: Verify pytest Installation
      run: |
        echo "Verifying pytest is installed..."
        pytest --version || echo "pytest is not installed, check dependencies."

    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest --cov=.  # Run tests with coverage reporting

    - name: Generate Lock File
      run: |
        echo "Generating conda-lock file for reproducibility..."
        conda install -c conda-forge conda-lock
        conda-lock lock --file environment.yml
